### ISSUE TITLE
No room names in 2.0 beta 

### ISSUE THREAD

**Issue by stefanbergh** [harriedegroot/nl.hdg.mqtt#12]
The room names are not in the topic. 

All devices ar just under 'home' as in these picture:

![image](https://user-images.githubusercontent.com/2189621/52489546-d6dd7c00-2bc2-11e9-8e3c-7a41bc62aa37.png)
![image](https://user-images.githubusercontent.com/2189621/52489589-ed83d300-2bc2-11e9-9901-fcb9344b2ec3.png)

**Comment by harriedegroot** [comment]
beta or homie2 branch?

**Comment by stefanbergh** [comment]
Beta 2.0.1

**Comment by harriedegroot** [comment]
Try homie2, beta branch is way behind. I will merge homie2 to beta soon.
