### ISSUE TITLE
getZones Error: An unknown error has occurred [session_expired]

### ISSUE THREAD

**Issue by illwillSE** [harriedegroot/nl.hdg.mqtt#13]
Hi!

Love what you're doing with the application and I appreciate your hard work.

I just reinstalled it (MQTT Hub) and when I start it now I get the errormessage shown in the topic. I might have missed something obvious but can't think of it right now.

I've verified that the mqtt client is working and I installed the beta version of it manually (since I didn't find the beta-version in the appstore) (https://github.com/scanno/nl.scanno.mqtt/tree/beta).

I'm running Homey 2.0.4

**This is the output when I run the app:**

Debugger listening on ws://0.0.0.0:9229/87b48cf3-8707-45f3-84fa-75dfcaca894d
For help see https://nodejs.org/en/docs/inspector
20190225-21:33:33   MQTT Hub is running...
20190225-21:33:33   object Object
20190225-21:33:33   PROPERTIES: {}
20190225-21:33:33   get system info
(node:6674) UnhandledPromiseRejectionWarning: session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6674) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
20190225-21:33:41   get zones
{ session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'session_expired',
  code: 401,
  cause:
   t {
     __athom_api_type: 'HomeyAPI.ManagerZones.Error',
     code: 401,
     error: 'session_expired',
     error_description: 'An unkown error has occured [session_expired]',
     '$stack': undefined } }
(node:6674) UnhandledPromiseRejectionWarning: session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
20190225-21:33:41   get devices
{ session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'session_expired',
  code: 401,
  cause:
   t {
     __athom_api_type: 'HomeyAPI.ManagerDevices.Error',
     code: 401,
     error: 'session_expired',
     error_description: 'An unkown error has occured [session_expired]',
     '$stack': undefined } }
(node:6674) UnhandledPromiseRejectionWarning: session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

**And this when I open the settings:**

20190225-21:33:41   get devices
{ session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'session_expired',
  code: 401,
  cause:
   t {
     __athom_api_type: 'HomeyAPI.ManagerDevices.Error',
     code: 401,
     error: 'session_expired',
     error_description: 'An unkown error has occured [session_expired]',
     '$stack': undefined } }
(node:6674) UnhandledPromiseRejectionWarning: session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
20190225-21:36:51   get zones
{ session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'session_expired',
  code: 401,
  cause:
   t {
     __athom_api_type: 'HomeyAPI.ManagerZones.Error',
     code: 401,
     error: 'session_expired',
     error_description: 'An unkown error has occured [session_expired]',
     '$stack': undefined } }
(node:6674) UnhandledPromiseRejectionWarning: session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
20190225-21:36:51   get devices
{ session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'session_expired',
  code: 401,
  cause:
   t {
     __athom_api_type: 'HomeyAPI.ManagerDevices.Error',
     code: 401,
     error: 'session_expired',
     error_description: 'An unkown error has occured [session_expired]',
     '$stack': undefined } }
(node:6674) UnhandledPromiseRejectionWarning: session_expired: An unkown error has occured [session_expired]
    at /node_modules/athom-api/dist/index.js:1:1045125
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:6674) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

**Comment by illwillSE** [comment]
Seems to be working now with the 2.0.5 rc.2 update

**Comment by harriedegroot** [comment]
Closing as it's reported resolved.
