### ISSUE TITLE
hub 2.1.5 and homey 2.0.5

### ISSUE THREAD

**Issue by satbopper** [harriedegroot/nl.hdg.mqtt#15]
the version 2.1.5 keeps searching for devices,even if you have disabled the app in homey it keeps on searching for devices ever ever ever forever
sorry maybe the next version works again because i had to remove it otherwise it will lock up my homey

**Comment by RedBarroth** [comment]
I have a similar issue. I have just installed the app and when I come to the step choose devices your devices. It just keeps spinning and it never displays the list of devices to choose from.

**Comment by harriedegroot** [comment]
This issue is fixed in version 2.1.6.

App is already submitted to the store (waiting for approval from Athom).
You can already install the master branch via CLI.
