### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Asinke** [harriedegroot/nl.hdg.mqtt#17]
Hi Harrie,

Thanks for this superb app, really like it. What would be even better if the app would also publish the Enelogic devices and Solar panels. The latter is published with empty values. Not sure to designate this as a bug. Happy to provide additional information and or be part of beta testing. Current version is the latest RTM from the appstore

**Comment by harriedegroot** [comment]
Sounds like a bug in the app for your solar panels. The MQTT Hub does not have any device or app specific logic. You should probably contact the developer of your non published devices.
