### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by horstefan** [harriedegroot/nl.hdg.mqtt#18]
publish flows and their statuses to MQTT
-Enabled Boolean/setable
-Trigger(ed)  Boolean/setable

publish logic (and better logic) variables to MQTT

publish CountDown timers to MQTT

**Comment by harriedegroot** [comment]
Isn't all of this already possible with the flowcards from the MQTT Client? Maybe combined with an MQTT Device here and there (beta version Hub)?

Can you elaborate on any bugs?

**Comment by horstefan** [comment]
i think it might be. however creating a separate (MQTT) flow for every variable/flow/timer seems like a workaround ;)

so these are no bugs, only requests :)

**Comment by harriedegroot** [comment]
It is simply not possible to tap into the flows. Had a long discussion about this once, the creator of homey (WeeJeWel)    concluded it's not possible.

**Comment by horstefan** [comment]
tragic. thank you for explaining
