### ISSUE TITLE
Openhab2 dont Control homey-device

### ISSUE THREAD

**Issue by tohmc** [harriedegroot/nl.hdg.mqtt#19]
Hi,

I am a newbe in mqtt.

I installed on Homey (2.1.2):
mqtt broker v1.0.5 (menno van grinsven)
Mqtt Client v2.2.2 (menno van grinsven)
Mqtt hub v2.1.9 (herrie de groot)

On my Computer (Windows Client)
I installed Openhab2.4

Then i configured the Homey Apps like in discription of These.

When i „sniff“ with mqtt Explorer i See changes in the value onoff (True or false) when i Toggle an shelly (inplemented with Homey shelly App).
So far so good.
That means that hub and broker is working?

Than i Configured openHAB with one Test Switch. And link it to the mqtt Broker Homey App.
When i toggle the shelly from Homey App it changes the State of the Test item in openHAB.
That means that openHAB is good too?

 But when i toggle the Test item from openHAB nothing changes on Homey App (and the shelly isnt toggled) But on mqttexplorer i See the same changes in onoff value (true and false) as i would toggle it from Homey App.

I think there is something wrong in Homey.

Homey mqtt client and openHAB have two separate userid‘s.
I also Test it with the same userid But the problem is the same.

Can you help me to Control my homey devices through openHAB?
Regards

**Comment by tohmc** [comment]
I tested all these with an shelly.
It’s the same problem.
Any ideas?

**Comment by tohmc** [comment]
It works when I create an Flow that is controlling the shelly.

But I think it’s not the way it have to work or?

Is there missing an link back from client to hub or hub to shelly.

**Comment by tohmc** [comment]
harriedegroot

Any ideas?

**Comment by harriedegroot** [comment]
Try rebooting all apps via the app config menu in this order: broker, client, hub

**Comment by harriedegroot** [comment]
This sounds like a configuration 'issue'.
For further support try the [forum](https://community.athom.com/t/mqtt-hub-gateway).
Feel free to open a new ticket if any problems remain or if there's a specific bug or problem with the hub.

**Comment by tohmc** [comment]
Sorry but that’s dont solve my problem.

I restarted several times an reinstall the applications.
But still the same.

I see all devices publishing mqtt messages in mqtt Explorer but I can’t control these without making an flow that „subscribes“ the specific message to control the device.

In my opinion the mqtt Hub have to work without flows. Is it right?

What can be the configuration issue that you are talking about?
