### ISSUE TITLE
Value 0 (zero) shown as empty space, or 'Onbekend'

### ISSUE THREAD

**Issue by vogon1** [harriedegroot/nl.hdg.mqtt#21]
Zero values are not shown as 0, it is an empty value.
Also using MQTT explorer, 0 is not shown.

![Screenshot 2019-06-15 at 17 04 26](https://user-images.githubusercontent.com/177368/59553033-a736ea00-8f8f-11e9-9b6c-74c853575872.png)

Is this indeed a MQTT Hub issue?
Can this be solved?

**Comment by vsurlien** [comment]
Same issue:

![image](https://user-images.githubusercontent.com/15659678/111023040-f7e2ad80-83d6-11eb-9d67-706d908b3344.png)

Can this be solved?

**Comment by harriedegroot** [comment]
Created a pull request for the MQTT Client app:
https://github.com/scanno/nl.scanno.mqtt/pull/27

**Comment by harriedegroot** [comment]
added workaround: https://github.com/harriedegroot/nl.hdg.mqtt/commit/a4d9d9a1859329653152e1855d259075a3c9f2c3

Will be included in MQTT Hub version 3.1.1
