### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tohmc** [harriedegroot/nl.hdg.mqtt#22]
First off all thank you for your great work.

Is it possible to implement In mqtt device more than one time an capability to one device?
For example:
I want to use an device with Two Relays (onoff) one is relay/0 and one is relay/1 and two contact sensor devices (contact_alarm)
To Generate an Garagedoor out of multiple devices.

It already works with one contact sensor and one Relay. Because of the Limitation to use only one time the capability onoff I can’t add a second.

**Comment by tohmc** [comment]
It is possible to add specific capability’s?
When maybe a device don’t send onoff in Power or so.

Shelly devices with mqtt enabled and set to rollershutter send roller/0 Open/stop/close
There is actually no chance to add it via
add-> MQTT device if I want to combine it with additional sensor.

**Comment by tohmc** [comment]
Any idea?

**Comment by harriedegroot** [comment]
First of all, sorry for this late response...

Technically it's possible to add a capability more then once.
See the docs: https://apps.developer.athom.com/tutorial-Drivers-Capabilities.html

The implementation has some impact on both the logic of adding capabilities (current implementation assumes it's unique, adds a filter, etc.) and the interface (detect duplicates & be able to provide a unique name per capability). The code for adding capabilities can be found here: https://github.com/harriedegroot/nl.hdg.mqtt/blob/beta/drivers/device/driver.js r118

I will add this request to the bucket list, but I'm afraid I wont be implementing this feature any time soon, sorry....
Feel free to create a pull-request though.

**Comment by tohmc** [comment]
Hi,

Thanks,

I will check if I can do a pullrequest,
(Im not a coder but I would learn it)

Does it mean that you never implement it or not in the next time ?

**Comment by albertjSmit** [comment]
Hi, love the Homey-Hub app!

It would be nice to activate the Broadcast with a Homey Flow, or is there another option to automate a broadcast of device status?

**Comment by harriedegroot** [comment]
Unfortunately, a flow card to trigger the broadcast is not implemented. An alternative for now is to send a so called 'birth' message. The hub automatically performs a broadcast when it receives such a message.

**Comment by harriedegroot** [comment]
flow card trigger is implemented
