### ISSUE TITLE
Bug/Feature er noob error

### ISSUE THREAD

**Issue by Asinke** [harriedegroot/nl.hdg.mqtt#23]

**Comment by Asinke** [comment]
I'm using Fibaro Dimmer 2 for controlling a light. But also use its S2 input connected to a momentary switch to trigger a flow in homey.

The light is published as expected in Mqtt, but the switch capability seems not

![image](https://user-images.githubusercontent.com/32021588/62818540-e37a6700-bb48-11e9-8fc9-6cbc6479e995.png)

Any plans to add this functionality?

**Comment by harriedegroot** [comment]
The MQTT Hub has no device specific functionality. It operates on all available capabilities exposed by the device drivers. The Fibaro driver does not contain a capability for the S2 input of the Dimmer 2. Additionally, there is no possibility to access device flow triggers or actions from within apps, so triggering the S2 input from code is a no go...
