### ISSUE TITLE
$name on switches

### ISSUE THREAD

**Issue by ksvan** [harriedegroot/nl.hdg.mqtt#24]
Great app for Homey! Using it now with Home Assistant, Homey Pro with 2.5.2. Standard mqtt client on Homey and mqtt broker on a ubuntu box with home assistant and Node-red. 
It seems like the topics for devices are using the actual name i would expect, but the $name topic below is different. 
Ie Virtual Device button called Home has Topic Homie/homey/home, but the $name says "Home - Turned on". Seems to be the same for all Fibaro, aotec and Virtual switches, but not for Sonos switches. And home assistant use $name as the so called "friendly name", that is shown all over

**Comment by harriedegroot** [comment]
Should be solved in version 3.1.8

**Comment by harriedegroot** [comment]
Reverted the change since other users report it as 'broken'. Consider it 'by design'...
