### ISSUE TITLE
Can't install the app.

### ISSUE THREAD

**Issue by JAltberg** [harriedegroot/nl.hdg.mqtt#26]
Hi!

Problem started with that I could not control my lamps through Google Home. All sensor seams to be working, but not lamps. Homey talks to Home Assistant by mqtt (this app) and then from HA to GH. Did some reboots, but nothing seemed to be working.

So I uninstalled Mqtt hub and now I can't get it installed.

Will switch over from Homey to Conbee later next week... But would be nice to get it working in the meantime.

Se images:
 
![image](https://user-images.githubusercontent.com/43683630/68957708-e382a680-07ca-11ea-9241-13cd1b982f4b.png)
![image](https://user-images.githubusercontent.com/43683630/68958215-f3e75100-07cb-11ea-838a-4b229d38553c.png)

**Comment by harriedegroot** [comment]
This is probably an issue with your Homey version? I saw people reporting similar issues for other apps (slack channel), which were resolved by updating Homey to the latest (stable) version...

**Comment by harriedegroot** [comment]
Closing this issue, please re-open if installation still fails.
