### ISSUE TITLE
Translations "issue" between homey versions

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [harriedegroot/nl.hdg.mqtt#27]
In homey version 3.0 with mqttt hub I had the topic  */sensor/**thuis**/ls120p1/#  but in homey v3.1.0 the topic name is changed to */sensor/**home**/ls120p1/# 
So my node-red dashboard was not updated anymore. took a while to find this :)

Can you change mqtt hub that only english language is used in all system topics and no translations?  Will also make sharing topics in node-red flows more easy between users international.

Regards, Marco

![mqtt hub and homey translations in mqtt](https://user-images.githubusercontent.com/28575285/68992022-e2eb1e00-0865-11ea-86d7-913c02e2cefa.png)

**Comment by harriedegroot** [comment]
Zones are just a list of names provided by Homey. 
There is no possibility to control the language.
