### ISSUE TITLE
MqttHub stops working after automatic Homey firmware update

### ISSUE THREAD

**Issue by val-arg** [harriedegroot/nl.hdg.mqtt#28]
MqttHub stops working properly after automatic Homey firmware update.
It doesnt receive mqtt messages & doesn't send mqtt messages to some topics. So some devices work fine and others don't.
After manual app restart everything works again.

**Comment by harriedegroot** [comment]
Probably a (socket) connection issue between the Hub & Client. Can't do much about it from within the hub.
Solved by restarting the app.
