### ISSUE TITLE
Can't change topic or on/off values of MQTT device

### ISSUE THREAD

**Issue by giggo** [harriedegroot/nl.hdg.mqtt#31]
(Version 2.2.5, Homey 3.2.0)

If I try to change any topic or the "On/Off values" of a MQTT device (light with onoff capability) I get a timeout when saving the settings. 
Nothing shows up in debug log in app. Any idea?

**Comment by bjwelker** [comment]
Same Porblem here pls pls fix hat :-(

**Comment by mvaneijken** [comment]
In my case there seems no way to control a device published through the MQTT Hub. 

Things I've tried for a device named "grote-lamp":
`homie/homey/grote-lamp/onoff/set` = true for on, does not work also when sending "string" "true"
`homey/$command` with message `{
  "command": "set",
  "device":{
    "name": "grote-lamp"
  },
  "value": true
}` (also tested with a "string" "true").

Reading the status of the devices is no problem.

I'm using the MQTT Broker v.1.0.5 on the Homey itself and also the MQTT Client v.2.2.3.
I'm on MQTT Hub v2.1.9. Commands are send using Node Red or the MQTT Explorer.

To make sure if the broker works, I also have tried a Tasmota switch that listens directly through MQTT using the same broker and that device responds to the commands send to that device.

**Comment by leisegang** [comment]
i have that same problem, whenever i change a light in homeassistant to OFF it turns off and then 2 seconds later it turns ON. The payload isnt getting through. 

What can be the problem?

**Comment by harriedegroot** [comment]
resolved in SDK v3 version
