### ISSUE TITLE
Feature request: Flow to start broadcast

### ISSUE THREAD

**Issue by dannymertens** [harriedegroot/nl.hdg.mqtt#32]
Hi,

First thanks for the great plugin, use this daily with Home Assistant and works flawless!

I don't know if its possible but now if we restart Home Assistant (what's frequently if your still playing with it :-P)  we need to do an manual broadcast to update the dashboard again.

I would like to create some kind of monitoring option (ping, nmap) on Homey that checks if HASS is online and put the status to a variable.
If the status changed to offline then I would like to start a flow to inform me and after the status changed back to online again start a flow to do a manual broadcast.

So my request is it possible to add a flow option for this to the MQTT hub plugin so we can use this in a flow?

Thanks!!

**Comment by harriedegroot** [comment]
This is already possible using the birth & last will messages. The Hub automatically broadcasts when it receives a birth message from HA.

Adding a flow trigger is a great suggestion and was already on the list, but with low priority...

**Comment by harriedegroot** [comment]
Additional: the current version (install via CLI) contains a small fix in retaining certain messages so a broadcast isn't even necessary in some cases.

**Comment by dannymertens** [comment]
> Additional: the current version (install via CLI) contains a small fix in retaining certain messages so a broadcast isn't even necessary in some cases.

I really use this for a lot of dashboards, so must be completely stable, don't want to have discussions with the wife about this ;-) so is this a test version then I probably wait for the production version, or can I safely install this on a production environment?

Thanks for the great work!
