### ISSUE TITLE
Homey reboot missing home assistant entities from broadcast

### ISSUE THREAD

**Issue by jacquesvzijp** [harriedegroot/nl.hdg.mqtt#35]
Hi Harry,
I noticed that some of my sensors got frozen. I have been trying to isolate and re-produce the problem.
I do a nightly restart of my Homey at 05:00AM. I found that MQTT hub is properly restarting and automatically broadcasting the home assistant discovery, except for my Fibaro devices. My guess is a timing issue between restart of the Fibaro driver not being fully started before MQTT Hub does the broadcast. Attached you can see two PIRs one being a NEO Coolcam (woonkamer) and the other Fibaro (voordeur). You can notice the time of the config record. 
I have built a work around to redo the broadcast at 05:15.

Setup:
- Homey
- MQTT Broker on Docker on Synology
- Home Assistant on Docker on Synology

Regards,
Jacques

<img width="979" alt="Screenshot 2020-07-10 at 12 18 37" src="https://user-images.githubusercontent.com/31371857/87144549-35bb8f00-c2a8-11ea-9810-dc6586f0bea3.png">
<img width="979" alt="Screenshot 2020-07-10 at 12 19 16" src="https://user-images.githubusercontent.com/31371857/87144554-381de900-c2a8-11ea-9043-2a91b10c31a7.png">

**Comment by harriedegroot** [comment]
Is the issue solved with the latest (test) version of both the MQTT Client & Hub?

**Comment by harriedegroot** [comment]
Closing this issue, just re-open if its not solved by updating to MQTT Hub app v3+
