### ISSUE TITLE
Inconsistency in published information

### ISSUE THREAD

**Issue by rkokkelk** [harriedegroot/nl.hdg.mqtt#38]
Hi first of all, thanks for the great work on this app. 

However, recently I've run into issues where the status (power / temperature) of certain devices are not published. E.g I've got a device which gather weather information for which the info is correctly and timely published, however recently e.g. the temperature in the thermostat is published only twice a day. While it frequently changes and in Homey the proper temperature is shown but not in MQTT.

The same happens for power, although the homey App correctly shows the power output, the published status in MQTT remains empty. Even clicking the _Broadcast all devices_ option does not result in any value being published. 

Does anyone has any idea on what the origin is of this. The current setup run perfectly the first couple of weeks but recently the aforementioned bugs appeared.

* Homey `4.2.0`
* MQTT Client `2.2.3`
* MQTT Hub `2.1.9`

**Comment by harriedegroot** [comment]
Did you try restarting the mqtt client app?

**Comment by rkokkelk** [comment]
I just tried it, then again pressed _Broadcast all_ button but alas no difference in temperature and power are not updated to the proper value.

**Comment by harriedegroot** [comment]
Try restarting both mqtt client & hub apps (in this order). You're probably
looking at retained messages at the broker...do you see any new messages
coming in form the hub? Personally I'm using 'mqtt explorer' to monitor the
raw data.

**Comment by rkokkelk** [comment]
I'm also using mqtt explorer for viewing the raw data. Restarting both apps did indeed resolve this issue for now.

However, I'm wondering what the initial issue would be. I'm already rebooting homey once a week and would love to keep using both apps without manually restarting it once in a while.

**Comment by harriedegroot** [comment]
There is a (un)known issue with the socket connection between the apps.
Sometimes the mqtt client just does not forward the messages anymore...I
know some people restart the app via a flow the prevent this from
happening. Unfortunately I do not have a better solution for now...at least
you're back in business!
