### ISSUE TITLE
Strange behavior MQTT Hub

### ISSUE THREAD

**Issue by JeroenKokhuis** [harriedegroot/nl.hdg.mqtt#39]
Hello,

Thanks for the great app. I have a strange problem with 2 Fibaro roller shutter switches. 

If I send a message to topic: `homie/homey-xxxxxxxxxxxxxxxxxxxxx/windowcoverings/Slaapkamer Liam/Rolluik/dim` then a message is simultaneously sent to topic:` homie/homey-xxxxxxxxxxxxxxxxxxxxxxxxx/windowcoverings/Slaapkamer Ons/Rolluik/dim`

![image](https://user-images.githubusercontent.com/53951988/91034222-f1404480-e604-11ea-98b3-f8bbb1483152.png)

and I can't figure out why this is happening. I thought it was node red. But after I shutdown Node Red it still occurs

**Comment by harriedegroot** [comment]
Sorry, no clue. Strange behavior. Are you sure the Hub is responsible for these duplicate messages? The hub does only trigger on device state changes.

**Comment by JeroenKokhuis** [comment]
I changed the name of the devices (because I had 2 devices with the same name :Rolluik) and the problems are gone.
