### ISSUE TITLE
Specific device updates not published by MQTT hub

### ISSUE THREAD

**Issue by stofferr** [harriedegroot/nl.hdg.mqtt#40]
Hi,

I have a homey pro, and many devices. Since recently (after several weeks of flawless operation) exactly one device, Zonnepanelen/Solar panels (SolarEdge Omvormer to be specific) does not have its updates published on MQTT. 

I tried restarting Homey, forcing a manual broadcast, restarting the app, nothing worked, except for removing and adding the device.

Now, after several days, the same problem appears: no updates published since yesterday ~7pm CET when the 'current value' reached 0.

The device itself works properly. All values are reported in the SolarEdge App without any issues. Homey has the same values, in the device details page as well as the Energy page, so no problems from that point of view.

Nevertheless, this exact same device does not have its values published on homey after some time. 

Thanks

**Comment by harriedegroot** [comment]
This is really hard to debug...can you find anything related in the logs?
The hub has not changed since months....Maybe it's a bug/limitation in the Homey core (firmware)? I know Homey blocks flows when they consume a lot of resources, maybe they do something similar for 'busy' devices. Furthermore many people report network related issues. Did the issue start after you updated Homey?

My personal SolarEdge is connected to HA using the netbus interface (yes I completely migrated to HA, don't use my Homey anymore). It provides frequent updates (every sec.?). So maybe your converter is 'spamming' mqtt messages and overloading the socket connection. Is it possible to reduce the update frequency in the SolarEdge app?

**Comment by stofferr** [comment]
- The Solar Panels component is working properly. It is updated every 15 minutes sharp.
- I am not using a flow to publish anything on MQTT
- I did not update Homey
- There are no MQTT messages registered on the MQTT Broker, so I assume they are not sent at all
- the update frequency of 15 minutes cannot be changed by the user

I have a workaround now to use the SolarEdge node on node-red so now I see the same info on Homey as on node red, just not over MQTT but with a direct node link. 

I don't know how to create a log....

I understand if the above does not give you a lot of details to progress.

**Comment by stofferr** [comment]
Hi, just a small update:

A few days ago Ziggo had an internet outage, which led me to reboot routers and switches and all other equipment in my house just to rule out I had an issue. 

Sure enough, after everything was working again, my plugwise smile P1 stopped communicating over MQTT. It did hwoever work correctly inside homey, so I could see correct usage and meter results.

I tried: 
- resetting homey - no result
- restarting the app - no result

Because I did not want to remove and add the device and lose my insights like had happened for my solaredge inverter, I looked for other options. 

In the end, inside the MQTT Hub app settings there is a device tab. I disabled and enabled the switch for the P1 device, and everything was working again.

This leads me to believe the issue is inside MQTT Hub.

I have a few suggestions for resolving - should you be willing to accept the proposals:
- can you publish this workaround in the documentation
- can you have a setting to automatically reset or disable+enable every day at a given time for a device or for all devices or something of this kind?

Thanks!

**Comment by Largus72** [comment]
Hi, 
I'm having a similar problem.

I have 4 Aquara motion sensors and 2 Xiaomi light sensor that don't update values after a restart of my Homey.
My Homey is restarting with a schedule every night at 4 and after that I don't get these values anymore in my Home Assistant.
Manually Broadcast does not work.
I found out that the only thing that is working, is changing the HOME CONVENTION from "Homie Convention v3.0.1" to "Custom" or from "Custom"  to "Homie Convention v3.0.1".
So it doesn't matter in what way I change this setting, it seems that the Broadcast which is done after changing this setting is just a little bit different than a normal Broadcast. After this change and automatic Broadcast, all values are available again in my Home Assistant and changing regularly.

So as with Stofferr I also like to have a setting that can automatically do the Broadcast that is running after changing the HOME CONVENTION, but then without actually changing the HOME CONVENTION :)

Thanks

**Comment by harriedegroot** [comment]
Some improvements are made.
Please try again with latest (test) version of both the MQTT Client & Hub.

Feel free to reopen if the issue isn't solved.

**Comment by stofferr** [comment]
Mijn mqtt broker wil momenteel niet starten. Ik kan pas over een week of 4 kijken waarom niet. Toch alvast dank! Ik waardeer het zeer!

⁣Get BlueMail for Android ​
