### ISSUE TITLE
IKEA Fyrtur shades aren't working with MQTT Hub and Home Assistant

### ISSUE THREAD

**Issue by woutf** [harriedegroot/nl.hdg.mqtt#41]
My Fyrtur blinds that are directly paired to Homey don't seem to work through the MQTT Hub. When controlling the blinds from Homey, the correct value is sent to the broker to mirror the current state. But when I change the value on the broker, nothing happens on Homey.  All other devices just work out of the box, both ways. Is this expected behavior? Someone on Slack recommended I make a flow on Homey that listens for changes on that certain topic and then passes it through to the device. This only works partially, if I change 'windowcoverings-set' in the broker from 100 to 0, which should lower the blinds from fully open to closed, it just moves about 15% of the way and then stops

Also, in the changelog it says that in 2.1.8 'HA Discovery: covers/blinds' was added, but it doesn't show up for me in HA. Needed to add it manually. Well, sensor.blinds_battery shows up, but not an entity that lets me control them

**Comment by harriedegroot** [comment]
Do you see any errors in the HA log regarding the blinds config for HA discovery? I expect HA to be ignoring mqtt configurations containing invalid keys (probably 'icon'). 

I've no clue why your blinds open only for 15%. The hub just forwards the value to the device capability.

**Comment by woutf** [comment]
I'm new to HA, hadn't found the logs yet. But yes, I do see errors.

> 2020-10-07 21:05:37 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_cover_mqtt': ({'name': 'Blinds', 'unique_id': '726f3b07-3c62-40ed-abb2-b76cb951e9ca_cover', 'value_template': '{{ value }}', 'position_topic': 'homie/homey-wout/blinds/windowcoverings-set', 'position_closed': 0, 'position_open': 1, 'position_command_topic': 'homie/homey-wout/blinds/windowcoverings-set/set', 'set_position_template': '{{ value }}', 'device': {'identifiers': 'homey-5efc92ab6e029d72ba3f92e1_726f3b07-3c62-40ed-abb2-b76cb951e9ca', 'name': 'Blinds'}, 'platform': 'mqtt'},)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/mqtt/cover.py", line 187, in async_discover
>     config = PLATFORM_SCHEMA(discovery_payload)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
>     return self._exec((Schema(val) for val in self.validators), v)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
>     raise e if self.msg is None else AllInvalid(self.msg, path=path)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
>     v = func(v)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
>     return schema(data)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
>     return base_validate(path, iteritems(data), out)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
>     raise er.MultipleInvalid(errors)
> voluptuous.error.MultipleInvalid: extra keys not allowed @ data['position_command_topic']
> 

By the way, this also happens with a Qubino-relay I've attached to my mechanical ventilation. In Homey I've set the attached device to 'fan', but according to the logs it's being discovered as a light and throws an error. 

> 2020-10-07 21:05:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'Ventilation', 'unique_id': '9a38f208-25bc-4879-8ce1-6501fe8376bd_light', 'payload_on': 'true', 'payload_off': 'false', 'state_topic': 'homie/homey-wout/ventilation/onoff', 'state_value_template': '{{ value }}', 'command_topic': 'homie/homey-wout/ventilation/onoff/set', 'on_command_type': 'brightness', 'icon': 'mdi:toggle-switch-off-outline', 'brightness_state_topic': 'homie/homey-wout/ventilation/dim', 'brightness_command_topic': 'homie/homey-wout/ventilation/dim/set', 'brightness_value_template': '{{ value }}', 'brightness_scale': 100, 'device': {'identifiers': 'homey-5efc92ab6e029d72ba3f92e1_9a38f208-25bc-4879-8ce1-6501fe8376bd', 'name': 'Ventilation'}, 'platform': 'mqtt'},)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 55, in async_discover
>     config = PLATFORM_SCHEMA(discovery_payload)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__
>     return self._exec((Schema(val) for val in self.validators), v)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec
>     raise e if self.msg is None else AllInvalid(self.msg, path=path)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec
>     v = func(v)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
>     return schema(data)
>   File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 32, in validate_mqtt_light
>     return schemas[value[CONF_SCHEMA]](value)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
>     return self._compiled([], data)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
>     return base_validate(path, iteritems(data), out)
>   File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
>     raise er.MultipleInvalid(errors)
> voluptuous.error.MultipleInvalid: extra keys not allowed @ data['icon']

**Comment by woutf** [comment]
Hi, is there any other input I could give to get to the origin of the problem?

**Comment by rindlerblabla** [comment]
@woutf Did you make it work in some way. Have also got a qubino dimmer with a fan connected to it, and got the same error in HA.

**Comment by woutf** [comment]
@rindlerblabla nope, afraid not.

**Comment by harriedegroot** [comment]
removed all icons from HA dispatcher payload
