### ISSUE TITLE
MQTT Hub only pushes battery level and battery alarm for Robb Smart Wall Switch

### ISSUE THREAD

**Issue by woutf** [harriedegroot/nl.hdg.mqtt#42]
Hi,

I'd like to use my Robb Smart Wall Switch through MQTT, but MQTT Hub only pushes two values to the broker: the battery level and the battery alarm. '$type=sensor'. The switch-functionality and the buttons are nowhere to be found. Can this be implemented?

**Comment by harriedegroot** [comment]
Nope sorry, that's not possible...
The hub only communicates device capabilities. Switches do not alter a capability on Homey, but execute a flow trigger (in most cases). Flow triggers (& conditions/actions) are only accessible from the app who declares them, so the hub can't listen to those changes.

**Comment by woutf** [comment]
Alrighty. Didn't know that, but it makes sense. Thanks.
