### ISSUE TITLE
Error on Mqtt editing

### ISSUE THREAD

**Issue by sdomotica** [harriedegroot/nl.hdg.mqtt#43]
I'm running Homey 4.20 and Mqtt Hub 2.2.5
When I try to edit On/off values schema or in Advanced Topic I receive a timeout message

![Mqtt01](https://user-images.githubusercontent.com/781294/96141430-4b70ce00-0f01-11eb-8a61-882ad1ebec36.png)
![Mqtt02](https://user-images.githubusercontent.com/781294/96141447-50ce1880-0f01-11eb-95d7-abd090014598.png)

**Comment by harriedegroot** [comment]
resolved with SDK v3?

**Comment by sdomotica** [comment]
Sorry if reopen. Bug it's solved. But now the payload for 0 and false is empty, for 1 and true is ok.
Ok for on/off.
I'm testing poweron/off for a light
Bye
Sandro

**Comment by harriedegroot** [comment]
That BUG is also resolved by now :)

**Comment by harriedegroot** [comment]
This is the commit: https://github.com/harriedegroot/nl.hdg.mqtt/commit/c871a1e1f669c4bd8e15925797cfe6dd09e305d6

**Comment by harriedegroot** [comment]
FYI: Also working on some other improvements of the MQTT Device, version will be bumped soon.

**Comment by sdomotica** [comment]
I just downloaded your github version, and now works, but I have a loop, when set the status, the status from the broker is published, and homey resend the command, in neverending loop.

**Comment by harriedegroot** [comment]
Are you able to remove: drivers/device/device.js r149
remove this line: 'await this._publishMessage(capabilityId, value);' 
in this file: https://github.com/harriedegroot/nl.hdg.mqtt/blob/master/drivers/device/device.js

and report back?

**Comment by sdomotica** [comment]
Now it's ok with commented row
thks a lot
Tomorrow I'll test other function as per termo etc
![immagine](https://user-images.githubusercontent.com/781294/112736491-77ce5300-8f53-11eb-9663-0a542d4c10e0.png)

**Comment by harriedegroot** [comment]
Thanks for testing!

Could you also try replacing replacing the line by this?

const value = parseValue(message, capability, this.percentageScale);
const currentValue = await this.setCapabilityValue(capabilityId);
if(value !== currentValue) {
    await this.setCapabilityValue(capabilityId, value);
    await this._publishMessage(capabilityId, value);
}

**Comment by harriedegroot** [comment]
note: I updated the code, previous had a typo 'setCapabilityValue' vs 'getCapabilityValue'

**Comment by harriedegroot** [comment]
The thing is:
If the value is changed from an MQTT message on the 'set' topic, the 'state' topic can/will be out of sync.
It depends on wheter the MQTT Device is responsible for keeping the state topic updated, or if it's a value managed by some external device.

**Comment by harriedegroot** [comment]
https://github.com/harriedegroot/nl.hdg.mqtt/commit/f4711e47c6a94613eaa67bb29d404d0a2001a09d

**Comment by sdomotica** [comment]
I commented the last 3 rows and this works fine
![immagine](https://user-images.githubusercontent.com/781294/112736925-c16c6d00-8f56-11eb-825a-32a2dc6d905e.png)

**Comment by harriedegroot** [comment]
Nice, thanks for your feedback!
