### ISSUE TITLE
HASS Discovery error: extra keys not allowed

### ISSUE THREAD

**Issue by DieterKoblenz** [harriedegroot/nl.hdg.mqtt#45]
`Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'Salontafel', 'unique_id': '3ba0fe1f-921d-4d77-8e77-3dcd2b2c4cb7_light', 'payload_on': 'true', 'payload_off': 'false', 'state_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/onoff', 'state_value_template': '{{ value }}', 'command_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/onoff/set', 'on_command_type': 'brightness', 'icon': 'mdi:toggle-switch-off-outline', 'brightness_state_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/dim', 'brightness_command_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/dim/set', 'brightness_value_template': '{{ value }}', 'brightness_scale': 100, 'device': {'identifiers': 'homey-56b1eab7e5b6128e37de573e_3ba0fe1f-921d-4d77-8e77-3dcd2b2c4cb7', 'name': 'Salontafel'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 55, in async_discover config = PLATFORM_SCHEMA(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 32, in validate_mqtt_light return schemas[value[CONF_SCHEMA]](value) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['icon']`

I'm receiving the following error for two lights. I am unable to figure out if this is a HASS discovery error or an implementation error on the Hub.

**Comment by DieterKoblenz** [comment]
I've added a complete error:

> Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'Salontafel', 'unique_id': '3ba0fe1f-921d-4d77-8e77-3dcd2b2c4cb7_light', 'payload_on': 'true', 'payload_off': 'false', 'state_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/onoff', 'state_value_template': '{{ value }}', 'command_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/onoff/set', 'on_command_type': 'brightness', 'icon': 'mdi:toggle-switch-off-outline', 'brightness_state_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/dim', 'brightness_command_topic': 'homie/homey-56b1eab7e5b6128e37de573e/salontafel/dim/set', 'brightness_value_template': '{{ value }}', 'brightness_scale': 100, 'device': {'identifiers': 'homey-56b1eab7e5b6128e37de573e_3ba0fe1f-921d-4d77-8e77-3dcd2b2c4cb7', 'name': 'Salontafel'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 55, in async_discover config = PLATFORM_SCHEMA(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 32, in validate_mqtt_light return schemas[value[CONF_SCHEMA]](value) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['icon']
Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'Eettafel', 'unique_id': 'e3608326-9155-4d09-9292-3d76ca767f0e_light', 'payload_on': 'true', 'payload_off': 'false', 'state_topic': 'homie/homey-56b1eab7e5b6128e37de573e/eettafel/onoff', 'state_value_template': '{{ value }}', 'command_topic': 'homie/homey-56b1eab7e5b6128e37de573e/eettafel/onoff/set', 'on_command_type': 'brightness', 'icon': 'mdi:toggle-switch-off-outline', 'brightness_state_topic': 'homie/homey-56b1eab7e5b6128e37de573e/eettafel/dim', 'brightness_command_topic': 'homie/homey-56b1eab7e5b6128e37de573e/eettafel/dim/set', 'brightness_value_template': '{{ value }}', 'brightness_scale': 100, 'device': {'identifiers': 'homey-56b1eab7e5b6128e37de573e_e3608326-9155-4d09-9292-3d76ca767f0e', 'name': 'Eettafel'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 55, in async_discover config = PLATFORM_SCHEMA(discovery_payload) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 218, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 340, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.8/site-packages/voluptuous/validators.py", line 336, in _exec v = func(v) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable return schema(data) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/__init__.py", line 32, in validate_mqtt_light return schemas[value[CONF_SCHEMA]](value) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict return base_validate(path, iteritems(data), out) File "/usr/local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: extra keys not allowed @ data['icon']
Exception in color_temp_received when handling msg on 'homie/homey-56b1eab7e5b6128e37de573e/hoofdlamp/color/v': '68' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 35, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 398, in color_temp_received self._color_temp = int(payload) ValueError: invalid literal for int() with base 10: '388.96000000000004'
Exception in color_temp_received when handling msg on 'homie/homey-56b1eab7e5b6128e37de573e/keuken/color/v': '100' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/debug_info.py", line 35, in wrapper msg_callback(msg) File "/usr/src/homeassistant/homeassistant/components/mqtt/light/schema_basic.py", line 398, in color_temp_received self._color_temp = int(payload) ValueError: invalid literal for int() with base 10: '500.0'

**Comment by DieterKoblenz** [comment]
`2020-11-27 21:54:13 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_light_mqtt': ({'name': 'Salontafel', 'unique_id': '3ba0fe1f-921d-4d77-8e77-3dcd2b2c4cb7_light', 'payload_on': 'true', 'payload_off': 'false', 'state_topic': 'homie/homey/salontafel/onoff', 'state_value_template': '{{ value }}', 'command_topic': 'homie/homey/salontafel/onoff/set', 'on_command_type': 'brightness', 'icon': 'mdi:toggle-switch-off-outline', 'brightness_state_topic': 'homie/homey/salontafel/dim', 'brightness_command_topic': 'homie/homey/salontafel/dim/set', 'brightness_value_template': '{{ value }}', 'brightness_scale': 100, 'device': {'identifiers': 'homey_3ba0fe1f-921d-4d77-8e77-3dcd2b2c4cb7', 'name': 'Salontafel'}, 'platform': 'mqtt'},)`

**Comment by jacquesvzijp** [comment]
Dieter, not sure if you resolved your problem already, but I reported the same before. Homey is for some devices adding an icon attribute in MQTT that cannot be handled at the HASS side. Only solution I found was to manually configure the MQTT device in configuration.yaml without the icon attribute, That works well.
Jacques

**Comment by harriedegroot** [comment]
removed all icons from HA dispatcher payloads
