### ISSUE TITLE
No messages published when mqtt server is started after the homey is started

### ISSUE THREAD

**Issue by dbuekenh** [harriedegroot/nl.hdg.mqtt#46]
When homey is starting again up after a power failure no messages are published when the mqtt server is started afterwards. 

1e824dfb-dcc9-47be-be9f-a283a096122e

To make it work i need to restart the mqtt hub app. Then everything works again.

Rgds Dirk

**Comment by Largus72** [comment]
Hi Dirk,

This has something to do with Homey not totally started when MQTT Hub is starting.

What I did is to make a flow after Homey restarted, for whatever reason:

![image](https://user-images.githubusercontent.com/37779484/100514314-e05b1e00-3173-11eb-8a7b-02c5288041d4.png)

In this way the MQTT Hub is started correctly and messages are published.

Onno

**Comment by dbuekenh** [comment]
Ho onno, thanks for your feedback but two points:
- In my flows i do not see how to trigger a homey restart, also in the actions of the flow i do not see how to restart apps, should install an app for this?
- Further i have the same issue after after a network hickup 
![Uploading 100538550...]

So the workarround also need to be applied with the connection to the mqtt server droppes. 

- It would be beter to identify the core issue this would create more stability when an unstable network environment.

Mqtt client 78476c31-07c0-454d-8eef-1d9639717b41
Mqqt hub fe1230e9-9088-45da-8742-8f31f4e19520

Rgds Dirk

**Comment by harriedegroot** [comment]
Some improvements are made.
Please try again with latest (test) version of both the MQTT Client & Hub.

Feel free to reopen the issue if things still fall apart.
