### ISSUE TITLE
Homey & MQTT hub stuck after changing IP of MQTT broker

### ISSUE THREAD

**Issue by lifeda** [harriedegroot/nl.hdg.mqtt#48]
Hi,

I had a lovely system running including Homey, MQTT Hub and MQTT client until yesterday. I had to move my broker to a new HW resulting in a new IP address. Changed the IP address in the MQTT client. MQTT Hub did not publish status of 2 new devices that I added to home, so I tried to re-scan the devices.
Seems I better did not do this. Homey became totally unresponsive so that I had to reboot and de-activate anything MQTT i.e. hub and client. Seems I am able to get the client to work again. But when I restart the hub, there are no devices found, just a spinning wheel and Homey becomes totally unresponsive again (no more connection to app or dev portal).

Seems that MQTT hub is eating up all system performance ( I cannot prove this as I dont get access to the systems. It just seems that only after de-activating the MQTT hub, the system is coming up again).

Any idea or recommendation?

Thanks for any help!!!

-Kai

**Comment by harriedegroot** [comment]
Some improvements are made.
Please try again with latest (test) version of both the MQTT Client & Hub.

Feel free to reopen if the issue isn't solved.
