### ISSUE TITLE
MQTT Hub publishing error

### ISSUE THREAD

**Issue by alechenne** [harriedegroot/nl.hdg.mqtt#49]
Dear all, first of all I want to thank you very much for the MQTT hub app; it's working fine and solving me a lot of things.

I my Homey pro, I use the MQTT broker, MQTT client and MQTT hub.

In the MQTT broket log, I have this:

20210306-17:13:35 Packet published 5396.5
20210306-17:13:35 Packet published 60.8
20210306-17:13:44 Packet published 320068
20210306-17:13:56 Packet published **{"system":{"bootId":"184e4d33-8296-4b7b-a9e3-a4125f0545dc","cloudId":"5e2edf68ff7f9c0c395ea106","hostname":"homey-5e2edf68ff7f9c0c395ea106","platform":"linux","release":"4.14.15-g3c513a6eca","arch":"arm","uptime":320559,"loadavg":[2.37255859375,2.70361328125,2.51904296875],"totalmem":511922176,"freememMachine":8998912,"freememHuman":"2%","cpus":[{"model":"ARMv7 Processor rev 10 (v7l)","speed":996,"times":{"user":439806200,"nice":445275600,"sys":693326300,"idle":1557144500,"irq":0}}],"date":"2021-03-06T16:13:56.939Z","dateHuman":"samedi 6 mars 2021 17:13:56","dateDst":false,"devmode":false,"nodeVersion":"v12.16.1","homeyVersion":"5.0.0","homeyModelId":"homey3s","homeyModelName":"Homey (Early 2019)","timezone":"Europe/Zurich","wifiSsid":"Lechenne_Salon","wifiAddress":"192.168.1.135:80","wifiMac":"38:81:d7:35:29:d5"},"timestamp":1615047236960}**

In the MQTT hub log, I got this:

20210306-17:13:56 **Error publishing message**
20210306-17:13:44 message: $stats/uptime with value: 320068
20210306-17:13:35 message: powerwall/battery-soc with value: 60.8
20210306-17:13:35 message: powerwall/home-power with value: 5396.5

It seems that the Homey system MQTT message isn't parsed correctly by the Hub; is it ocrrect? is there an issue? (I just parsed the payload in a json interpreter and it seems to me correct.

**Comment by leisegang** [comment]
i got this too
20210306-17:13:56 Error publishing message

when i set a light to ON it goes to off within 3 seconds. the light does not change state

**Comment by P4k3** [comment]
Same issue here :(

**Comment by harriedegroot** [comment]
Should be resolved with MQTT Client app v2.4.2

**Comment by alechenne** [comment]
> Should be resolved with MQTT Client app v2.4.2

Thanks @harriedegroot. I don't what solve the issue (MQTT Hub, broket or client) but I can now read the packet  {"system":{"bootId": ...}. MQTT Hub is still indicating an error but the packet is sent and can be read.

At least from my specific case, it's solved. Thanks.

**Comment by harriedegroot** [comment]
Did you also try with the test version of the MQTT Hub app?
https://homey.app/nl-nl/app/nl.hdg.mqtt/MQTT-Hub/test/

**Comment by alechenne** [comment]
> Did you also try with the test version of the MQTT Hub app?
> https://homey.app/nl-nl/app/nl.hdg.mqtt/MQTT-Hub/test/

Thanks for the advise. In between the MQTT Hub was officially released to version 3.1.0. I’ll check with this version. Kind regards.
