### ISSUE TITLE
On Beta 2.0 topics are not normalized.

### ISSUE THREAD

**Issue by RobertHerter** [harriedegroot/nl.hdg.mqtt#5]
Hello,

Topics are not Normalzed as stated:
Homey Name: Homey -> Topic: Homey/
Homey Name: Homey XXX -> Homey XXX/

**Comment by harriedegroot** [comment]
Fixed in version x.0.2

**Comment by RobertHerter** [comment]
Topic is now normalizes in Beta 2.01 but Homeyname not.
