### ISSUE TITLE
MQTT Hub device has a few issues

### ISSUE THREAD

**Issue by oh2th** [harriedegroot/nl.hdg.mqtt#50]
Thank you for the device capability for this test version 2.2.5, I found a few issues with the MQTT Hub device manual configuration:

1) When the device's Advance configuration On/Off is set to send 1 or 0, it sends "null" for "Off" instead of the value 0, value of 1 is sent correctly for "On" command.
2) When the device reports its state "homie/device/relay 1" or "homie/device/relay 0" , the relay state in Homey is not updated
3) stateTopics may become truncated

My sample is now configured as:
```
{
  "measure_power": {
    "stateTopic": "mFi/3port/port1/power",
    "setTopic": ""
  },
  "meter_power": {
    "stateTopic": "mFi/3port/port1/energy",
    "setTopic": ""
  },
  "measure_voltage": {
    "stateTopic": "mFi/3port/port1/volta",
    "setTopic": ""
  },
  "onoff": {
    "stateTopic": "mFi/3port/port1/relay",
    "setTopic": "mFi/3port/port1/relay/set"
  }
}
```

Pressing On button from the MQTT Hub device sends correctly:
`mFi/3port/port1/relay/set 1
`
However, when toggled Off the message sent is 
`mFi/3port/port1/relay/set (null)
`
when it should send
`mFi/3port/port1/relay/set 0
`

Then if I command the device from a shell
`mosquitto_pub -t 'mFi/3port/port1/relay/set' -m 1
`
or
`mosquitto_pub -t 'mFi/3port/port1/relay/set' -m 0
`
the relay state changes accordingly, but it is not shown in Homey for the MQTT Hub device. Power, Voltage and Energy are updated while mFi/3port/port1/relay = 1

And one more thing is that the topic for mFi/3port/port1/voltage was truncated into the configuration:
```
  "measure_voltage": {
    "stateTopic": "mFi/3port/port1/volta",
    "setTopic": ""
  },
```
And it is not possible to fix it from the advanced configuration as it goes into timeout

**Comment by harriedegroot** [comment]
Should be solved in v3.0.1
