### ISSUE TITLE
20210331-10:58:27 210331-10:58:27 Error publishing message

### ISSUE THREAD

**Issue by horstefan** [harriedegroot/nl.hdg.mqtt#52]
Getting alot of "Error publishing message" since last update(s)
Homey is handling mqtt really bad (delays >30s) in sending and reading messages.

**Comment by harriedegroot** [comment]
That's an issue of the MQTT Client and probably solved with the test version: v2.4.2 of the MQTT Client app.

**Comment by horstefan** [comment]
Ran the upgrade, looks better now! Thanks Harrie
