### ISSUE TITLE
Get error messages but it works correct

### ISSUE THREAD

**Issue by jeesnl** [harriedegroot/nl.hdg.mqtt#53]
I get the error that error: Error publishing message. But to me the message is send correctly. See attachment.

![E1298946-7DD0-48B8-A68B-E791D02652F2](https://user-images.githubusercontent.com/39216786/113429004-1afded00-93d8-11eb-9ed5-580d77d19b8b.png)

**Comment by harriedegroot** [comment]
Known bug in client.
Solved in version MQTT Client app v2.4.2 (test version).

**Comment by jeesnl** [comment]
Indeed solved in the new client version. 

Thanks. 

Verstuurd vanaf mijn iPad
