### ISSUE TITLE
Feature Request: Sometimes MQTT Hub stops sending mqtt updates - stop/start helps but could it be automated?

### ISSUE THREAD

**Issue by stofferr** [harriedegroot/nl.hdg.mqtt#54]
Hi,

I have an MQTT broker running on docker, with Watchtower deploying updates whenever they become available, which can be any time of the day.

Every time a new version of the broker is deployed, MQTT Hub loses its connection. A restart of the app suffices as the connection with the broker is re-established I guess.

Is it possible to send/receive probe messages from MQTT /Hub that are sent e.g. every 5-15 minutes (maybe configurable?), and when the status message is not received back by MQTT Hub within 1 minute, it tries to repair the MQTT broker connection? 

An increasing interval could be used to re-attempt repair if the first time it does not work. So for example it tries to repair, then retries after 5 minutes, then after 10, then after every 15 minutes until it succeeds.

Thanks,
Roger

**Comment by stofferr** [comment]
Hi Harrie, I'm not comfortable with using test versions. I hope you don't mind that I just wait and sit it out until your improvements become part of the main branch?
Thanks!
PS: Happy with your App and with how quickly and adequately you respond.

**Comment by harriedegroot** [comment]
I understand. But I advise you to install and try the test version and just revert to the 'stable' release (which actually is less stable) if anything isn't to your liking. You can flawlessly switch between the 2 versions and you won't lose any settings/configuration.

**Comment by stofferr** [comment]
How - I read somewhere to use ..../test as an App URL, but then I see the same 3.1.9 version as for production. I must be doing something wrong - sorry.... heeeelllppp.....?

**Comment by harriedegroot** [comment]
Test version of the MQTT Client app:
https://homey.app/nl-nl/app/nl.scanno.mqtt/MQTT-Client/test/

**Comment by stofferr** [comment]
Testing - fingers crossed. Have a nice night!
