### ISSUE TITLE
Home Assistant MQTT Cover - value template for position topic will be deprecated from 2021.6

### ISSUE THREAD

**Issue by joostvkempen** [harriedegroot/nl.hdg.mqtt#56]
Logger: homeassistant.components.mqtt.cover
Source: components/mqtt/cover.py:122
Integration: MQTT (documentation, issues)

Using 'value_template' for 'position_topic' is deprecated and will be removed from Home Assistant in version 2021.6, please replace it with 'position_template'

This is related to the fix you made earlier for the Fibaro Roller Shutter

**Comment by harriedegroot** [comment]
Adjusted in version 3.5.2.
See commit: https://github.com/harriedegroot/nl.hdg.mqtt/commit/d0d44a9f15a86ab1a28bec4acfd6ad9ef2983072
