### ISSUE TITLE
Feature request for MQTT device outputTemplate 

### ISSUE THREAD

**Issue by Veliferum** [harriedegroot/nl.hdg.mqtt#89]
Dear Harrie,

I would like to see an extra option in the outputTemplate from a MQTT Device, the problem now is that I need a JSON string in my MQTT Broker which will be processed by a ESP32 with this “https://github.com/BartGijsbers/CN105Gateway” software, which is controlling a Mitsubishi Ecodan Heat Pump.

The topic I need post to is "ECODAN\cmnd" and the value must be like {“SetRoomTemperature”:“21”} and I’m unable to format that in the outputTemplate. I myself am a professional C++ programmer for more than 40 years but I know very little of Java and how to make an apps for the Homey. I looked at your code "/drivers/device/device.js" and think the below change will do the trick. Topics will than look like 

{
  "target_temperature": {
    "capability": "target_temperature",
    "stateTopic": "ECODAN/tele/0x09",
    "setTopic": "ECODAN/cmnd",
    "valueTemplate": "Zone1_Room_Temp_Setpoint",
    "outputTemplate": "<<{\"SetRoomTemperature\" : \"#value#\"}>>",
    "displayName": "Test"
  }
}

The code change will remove “<<” and “>>” (the triggers that it is a special string) and swap “#value#” with the real value and send something like {“SetRoomTemperature”:”20”} on topic ECODAN\cmnd.

Maybe it is even possible as an extra option to enter something like “^^MyConvScript@#value#|ECODAN/cmnd|SetRoomTemperature” in the outputTemplate where “^^” is the trigger for the script call option, the “@” is the delimiter for the Name of the Script to call and the parameter for this script. The #value# in the parameter string will be swapped with the real value (assume 18) and the script MyConvScript will be called with the literal string parameter “18|ECODAN\cmnd|SetRoomTemperature” the parameter string can be anything and the #value# will always be swapped with the real value.

I hope you will have some spare time left to implement this.

Best regards,
Teun Pasterkamp

if(config.outputTemplate && config.outputTemplate.replace("{{", "").replace("}}", "").trim() !== 'value') {
  const template = config.outputTemplate;
  try {
    let state = this.getState() || {};
    state.value = payload;
    const mathjs = this.compiled.get(template);
    if(mathjs) { // math?
      payload = mathjs.evaluate(state);
    } else { // json-t
      **if(template.startsWith('<<')){
        payload = template.replace("<<", "").replace(">>", "").replace("#value#", value);
      } else {**
        if(!template.startsWith('{{') && (template.startsWith('{') || template.startsWith('['))) {
            payload = jsontObject(template, state);
        } else {
            payload = jsontString(template, state);
        }
      }
    }
 
  } catch(e) {
      this.log("failed to format output message", e);
  }
}

**Comment by harriedegroot** [comment]
It's already possible using the output template json-T notation
