### ISSUE TITLE
Homey Pro 2023 issues

### ISSUE THREAD

**Issue by looolz** [harriedegroot/nl.hdg.mqtt#90]
After migrating to the Homey Pro 2023, the MQTT Hub doesn't seem to work.

The app install fine on Homey Pro 2023, but no devices are reported when accessing the MQTT server hosted on Homey Pro.

**Comment by A-Wangen** [comment]
Hi, i also had this issue, but by checking off this option (Enable to Provide A Custom client ID that is used when connecting to the Broker)in MQTT Client data got populated. 
![image](https://github.com/harriedegroot/nl.hdg.mqtt/assets/43532832/6b42b28a-de30-413e-a683-2e312d60624d)

**Comment by looolz** [comment]
Thank you. That did the trick for me! Now I can finally move to the new Homey Pro 2023
